# Generated by Django 4.2.2 on 2023-06-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_pollingunit_polling_unit_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingunit',
            name='polling_unit_description',
            field=models.TextField(blank=True),
        ),
    ]
